---
    - name: Creating the user {{ ansible_operator }}
      user:
        name:  "{{ ansible_operator }}"
        create_home: true
        shell: "/bin/bash"

    - name: Add {{ ansible_operator }} user to the sudoers
      copy:
        dest:  "/etc/sudoers.d/{{ ansible_operator }}"
        content:  "{{ ansible_operator }}  ALL=(ALL)  NOPASSWD: ALL"

    - name: Deploy SSH Key to remote Machine
      authorized_key:  user={{ ansible_operator }}
                       key="{{ ansible_public_key }}"
                       state=present

    - name: Disable Password Authentication for all users
      lineinfile:
          path: /etc/ssh/sshd_config
          regexp: '^PasswordAuthentication'
          line: "PasswordAuthentication no"
          state: present
          backup: true

    - name: Disable Root Login
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: "PermitRootLogin no"
        state: present
        backup: true
      notify: restart_ssh

# tasks file for python_webhook