---
- name: get the Flux Package
  get_url:
    url: "https://github.com/fluxcd/flux2/releases/download/v0.31.1/flux_0.31.1_linux_amd64.tar.gz"
    dest: /tmp/flux.tar.gz

- name: Extract flux into /usr/local/bin
  become: true
  ansible.builtin.unarchive:
    src: /tmp/flux.tar.gz
    dest: /usr/local/bin
    remote_src: yes

