---
- name: testing bind9 role
  hosts: bind9
  tasks: 
    - name: installing bind9 role
      include_role:
        name: bind9
      vars:
        bind_listen_ipv4:
          - any
        bind_zones:
          - name: lab.local             # Domain name
            create_reverse_zones: true  # Skip creation of reverse zones
            primaries:
              - 10.0.0.3                # Primary server(s) for this zone
            name_servers:
              - bind9.lab.local.
            networks:
              -  "10"
            allow_update:
              - 10.0.0.200
            hosts:
              - name: bind9
                ip: 10.0.0.3
                aliases:
                  - ns1
              - name: ansible
                ip: 10.0.0.1
            forwarders:
              - 10.0.0.254