---
- name: testing bind9 
  hosts: ns1
  tasks: 
    - name: installing bind9 role
      include_role:
        name: bind9
      vars:
        bind_listen_ipv4:
          - any
        bind_allow_query:
          - any
        bind_zones:
          - name: lab.mylocal          
            create_reverse_zones: true  
            primaries:
              - 10.0.0.3                
            name_servers:
              - ns1.lab.mylocal.
            networks:
              -  "10"
            allow_update:
              - 10.0.0.200
            hosts:
              - name: ns1
                ip: 10.0.0.3
              - name: ns2
                ip: 10.0.0.4

- name: creating bind9 recursive server
  hosts: ns2
  tasks:
    - name: installing bind9 role
      include_role:
        name: bind9
      vars:
        bind_recursion: true
        bind_listen_ipv4:
          - any
        bind_allow_query:
          - any
        bind_forwarders:
          - 8.8.8.8
          - 8.8.4.4
        bind_zones:
          - forwarders:
              - 10.0.0.3
            networks:
              - "10"


            
