---
- name: testing bind9 role
  hosts: bind9
  tasks: 


    - name: installing bind9 role
      include_role:
        name: bind9
      vars:
        bind_zones:
          - name: lab.local             # Domain name
            create_reverse_zones: False  # Skip creation of reverse zones
            primaries:
              - 10.0.0.3                # Primary server(s) for this zone
            name_servers:
              - bind9.lab.local.
            hosts:
              - name: pub01
                ip: 192.0.2.1
                ipv6: 2001:db8::1
                aliases:
                  - ns1
              - name: pub02
                ip: 192.0.2.2
                ipv6: 2001:db8::2
                aliases:
                  - ns2
              - name: '@'                # Enables "http://mydomain.com/"
                ip:
                  - 192.0.2.3            # Multiple IP addresses for a single host
                  - 192.0.2.4            #   results in DNS round robin
                sshfp:                   # Secure shell fingerprint
                  - "3 1 1262006f9a45bb36b1aa14f45f354b694b77d7c3"
                  - "3 2 e5921564252fe10d2dbafeb243733ed8b1d165b8fa6d5a0e29198e5793f0623b"
                ipv6:
                  - 2001:db8::2
                  - 2001:db8::3
                aliases:
                  - www
              - name: priv01             # This IP is in another subnet, will result in
                ip: 10.0.0.1             #   multiple reverse zones
              - name: mydomain.net.
                aliases:
                  - name: sub01
                    type: DNAME          # Example of a DNAME alias record
            networks:
              - '192.0.2'
              - '10'
              - '172.16'
            delegate:
              - zone: foo
                dns: 192.0.2.1
            services:
              - name: _ldap._tcp
                weight: 100
                port: 88
                target: dc001
          # Minimal example of a secondary zone
          - name: acme.com
            primaries:
              - 172.17.0.2
            networks:
              - "172.17"
          # Minimal example of a forward zone
          - name: acme.com
            forwarders:
              - 172.17.0.2
            networks:
              - "172.17"

