---
- name: setting up kea server
  hosts: kea
  tasks:
    - name: Importing kea role
      include_role:
          name: kea
      vars:
        kea_dhcp4:
          Dhcp4:

            # dhcp-ddns
            dhcp-ddns:
              enable-updates: true
              

            # Add names of interfaces to listen on
            interfaces-config:
              interfaces:
                - "*"
              dhcp-socket-type: raw

            # Use Memfile lease database backend to store leases in a CSV file.
            lease-database:
              type: memfile
              persist: true
              lfc-interval: 0

            # Setup reclamation of the expired leases and leases affinity.
            expired-leases-processing:
              reclaim-timer-wait-time: 10
              flush-reclaimed-timer-wait-time: 25
              hold-reclaimed-time: 3600
              max-reclaim-leases: 100
              max-reclaim-time: 250
              unwarned-reclaim-cycles: 5

            ddns-qualifying-suffix: "lab.mylocal."
            ddns-update-on-renew: true

            # Global (inherited by all subnets) lease lifetime is mandatory parameter.
            valid-lifetime: 400
            renew-timer: 100
            rebind-timer: 200

            # Below an example of the simple subnet declarations
            subnet4:
              - subnet: 10.0.0.0/24
                pools:
                  - pool: 10.0.0.100 - 10.0.0.200
                option-data:
                  - name: routers
                    data: "10.0.0.254"
                  - name: domain-name-servers
                    data: "10.0.0.1"
                  - name: domain-name
                    data: "lab.mylocal"
                user-context:
                  note: Service network

              - subnet: 10.8.0.1/24
                pools:
                  - pool: 10.8.0.100 - 10.8.0.200
                option-data:
                  - name: routers
                    data: "10.8.0.254"
                  - name: domain-name-servers
                    data: "10.0.0.1"
                  - name: domain-name
                    data: "lab.mylocal"
                user-context:
                  note: Kubernetes network
                    
              - subnet: 10.254.0.0/24
                pools:
                  - pool: 10.254.0.100 - 10.254.0.200
                option-data:
                  - name: routers
                    data: "10.254.0.254"
                  - name: domain-name-servers
                    data: "10.0.0.1"
                  - name: domain-name
                    data: "lab.mylocal"
                user-context:
                  note: Personal network

        kea_dhcp_ddns:
          DhcpDdns:
            forward-ddns: 
                ddns-domains:
                  - name: "lab.mylocal."
                    dns-servers:
                      - ip-address: 10.0.0.1
                        port: 53

            reverse-ddns:
              ddns-domains:
                - name: "10.in-addr.arpa."
                  dns-servers:
                    - ip-address: 10.0.0.1
                      port: 53
