---
- name: Check if kubernetes nodes are reachable
  hosts: kubernetes
  tasks: 
    - name: Wait for connection to nodes
      wait_for_connection:

- name: Install Environment base
  hosts: kubernetes
  roles: 
    - ansible
    - qemuguest

- name: make kubernetes nfs server
  hosts: kube-nfs
  tasks:
    
    - name: include role nfs servers
      include_role: 
        name: nfs
      vars:
        nfs_exports:
          - /srv/nfs4                *(rw,sync,no_subtree_check,crossmnt,fsid=0)
          - /srv/nfs4/kubernetes     *(rw,sync,no_subtree_check)

- name: install kubernetes nodes
  hosts: kubernetes_workers
  roles:
    - containerd
    - kubernetes/node

- name: install kubernetes masters
  hosts: kubernetes_masters
  roles:
    - containerd
    - kubernetes/node
    - kubernetes/controller
  tasks: 
    - name: Install Python pre-requisits
      pip:
        name:
          - openshift
          - pyyaml>6.0
          - kubernetes 


- import_playbook: playbooks/kubernetes/initialize_cluster.yml

- import_playbook: playbooks/kubernetes/initialize_cluster_network.yml

- import_playbook: playbooks/kubernetes/worker_join_cluster.yml

- name: install kubernetes helm
  hosts: kubernetes_masters
  roles:
    - helm
    - helm/nfs-subdir

- import_playbook: playbooks/kubernetes/set_nfs_storage_class_as_default.yml


