---
- name: install kubernetes
  hosts: kubernetes-workers
  tasks:

    - name: include kubernetes role with worker var
      include_role:
        name: kubernetes
      vars:
        role: worker

