---
- name: Check if kubernetes nodes are reachable
  hosts: kubernetes
  tasks: 
    - name: Wait for connection to nodes
      wait_for_connection:

- name: Install Environment base
  hosts: kubernetes
  roles: 
    - ansible
    - qemuguest

- name: make kubernetes nfs server
  hosts: kube-nfs
  tasks:
    
    - name: include role nfs servers
      include_role: 
        name: nfs
      vars:
        nfs_exports:
          - /srv/nfs4                *(rw,sync,no_subtree_check,crossmnt,fsid=0)
          - /srv/nfs4/kubernetes     *(rw,sync,no_subtree_check)

- name: install kubernetes nodes
  hosts: kubernetes_workers
  roles:
    - containerd
    - kubernetes/node

- name: install kubernetes masters
  hosts: kubernetes_masters
  roles:
    - containerd
    - kubernetes/node
    - kubernetes/controller
  tasks:

- import_playbook: playbooks/kubernetes/initialize_cluster.yml

- import_playbook: playbooks/kubernetes/initialize_cluster_network.yml

- import_playbook: playbooks/kubernetes/worker_join_cluster.yml

- name: install kubernetes helm
  hosts: kubernetes_masters
  gather_facts: false
  roles:
    - helm
    - helm/nfs-subdir

  tasks:
    - name: Install pip
      become: true
      ansible.builtin.apt: 
        name: pip
        state: present

    - name: Install Python pre-requisits packages for managing kubenetes with Ansible
      pip:
       name:
        - openshift
        - pyyaml>3.11
        - kubernetes==11.00.0 
      vars:
        ansible_python_interpreter: /usr/bin/python3

- import_playbook: playbooks/kubernetes/default_stroge_class.yml

