---
- name: make a test nfs server 
  hosts: kube-nfs
  tasks:
    
    - name: include role nfs servers
      include_role: 
        name: nfs
      vars:
        nfs_exports:
          - /srv/nfs4                *(rw,sync,no_subtree_check,crossmnt,fsid=0)
          - /srv/nfs4/kubernetes     *(rw,sync,no_subtree_check)

- name: install kubernetes nodes
  hosts: kubernetes_workers
  roles:
    - containerd
    - kubernetes/node

- name: install kubernetes masters
  hosts: kubernetes_masters
  roles:
    - containerd
    - kubernetes/node
    - kubernetes/controller
    - helm
    - helm/nfs-subdir

- import_playbook: playbooks/kubernetes/initialize_cluster.yml

- import_playbook: playbooks/kubernetes/initialize_cluster_network.yml

- import_playbook: playbooks/kubernetes/worker_join_cluster.yml


