---

- name: pinging
  hosts: all
  tags: everyone
  tasks:
    - name: 'include ansible operator on all machines'
      include_role:
        name: ansible

    - name: install qemu quest agent on all machines
      ansible.builtin.apt:
        name: nginx
        state: absent
        update_cache: yes
      become: true

    - name: ensure 
      ansible.builtin.systemd:
        state: started
        name: Qemu