---

- name: pinging
  hosts: all
  tags: everyone
  tasks:
    - name: 'include ansible operator on all machines'
      include_role:
        name: ansible

    - name: apt-update
      command: apt update
      become: true

    - name: install qemu quest agent on all machines
      ansible.builtin.apt:
        name: qemu-guest-agent
        state: present
      become: true
      register: qemu_installed

    - name: Reboot a slow machine that might have lots of updates to apply
      reboot:
      when: qemu_installed.changed
      become: true

    - name: ensure Qemu guest agent is running on all machines. 
      ansible.builtin.systemd:
        state: started
        enabled: yes
        name: qemu-guest-agent
      become: true