---

- name: pinging
  hosts: all
  tasks:
    - name: 'hoi'
      include_role:
        name: ansible_client

- name: Deploy the terraform role on the terraform group
  hosts: terraform_servers
  tags: terraform
  tasks:
    - name: 'Deploying terraform role'
      include_role:
        name: terraform

    - name: 'Deploying terraform operator'
      include_role:
        name: operator
      vars:
        operator: terraform-op
        operator_shell: "/bin/bash"
        operator_sudo_rights: True
