---

- name: pinging
  hosts: all
  tags: everyone
  tasks:
    - name: 'include ansible operator on all machines'
      include_role:
        - name: ansible

    - name: 'include ansible operator on all machines'
      include_role:
        - name: qemuguest
    
