---

- name: pinging
  hosts: all
  tags: everyone
  tasks:
    - name: 'hoi'
      include_role:
        name: ansible

- name: Deploy the terraform role on the terraform group
  hosts: terraform
  tags: terraform
  vars:
    marc_ssh_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC9PdGQSxLdItzCZ/NNo+Pk2Hut7YKTaJiOvnPpJT0Td5CW3JrggnNJYF4+WmCSQ7XYlYw+Z6yV8sZu6ox1SoIYp/zvAbiMRqhKavj+mJ6i/wAx44sPeSxW/+/+Bl3aW66OsxGkX7JhmjzmuftQ7XAxOBYJNp8r1RTKKMq2jS7tvHevyC+6fjSbl/2fsyXjPPpBuGZ9wGDIWbLr/AHldulkOU+mmyxYyeW2EuBgGEB4qaybEf6aPkYP77pMMpbYnncqWzO02pn9IiE1+UtFMDDgwRw1aNV8RhfE5GRB9TA1poP27tfwvPq51w8MfKfAVFIPhuw6oNNOD2HWUyz3JkjAltSEjjUA4a3M3NFbWqIiY5tHws+Er2s0lsQSZwUrPJ2d0bXrTBJqLrc91R2CCKmou0Lki3gAeGHjABLNeJvaIf/IERuq9iEgTufHL7pWvKR34k+h+LjVL+KrUfW5WklfY9xkECUTp44wyInhc9RfZ2hsTkbkGr+FjnPkyfG5GrE= marchoogendoorn@AHoogendoorn
  tasks:
    - name: 'Deploying terraform role'
      include_role:
        name: terraform

    - name: 'Deploying terraform operator'
      include_role:
        name: operator
      vars:
        operator: terraform-op
        operator_shell: "/bin/bash"
        operator_sudo_rights: True
        operator_public_ssh_keys: "{{ marc_ssh_key }}"

    - name: deploy terraform vars
      import_playbook: ./playbook/deployment/deploy_terraform_variables.yml

