---

- name: pinging
  hosts: all
  tags: everyone
  roles:
    - ansible
    - qemuguest

  tasks:

    - name: install neofetch
      ansible.builtin.apt:
        name:  neofetch
        state: present
      become: true
      register: result
      until: result is successful
      delay: 6
      retries: 10
          