---

- name: pinging
  hosts: ALL
  tasks:
    ping:

- name: Deploy the terraform role on the terraform group
  hosts: terraform-servers
  tasks:
    - name: 'Deploying terraform role'
      include_role:
        name: terraform

    - name: 'Deploying terraform operator'
      include_role:
        name: operator
      vars:
        operator: terraform-op
        operator_shell: "/bin/bash"
        operator_sudo_rights: True
