---
operator_public_ssh_keys: []

operator: ''

hashicorp_key: "https://apt.releases.hashicorp.com/gpg"

# Defaults to amd64 or nothing 
architecture: "{{ 'amd64' if ansible_architecture == 'x86_64' else '' }}"

# For deb packages does this automaticly
repository_path: "deb [arch={{ architecture }}] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
# defaults file for foo