---
- name: Installing Pre-Reqs
  ansible.builtin.apt:
    name: "{{ kea_pre_reqs }}"
    state: present
  become: true
  register: result
  until: result is successful

- name: running kea setup script
  become: true
  shell:
    cmd: curl -1sLf 'https://dl.cloudsmith.io/public/isc/kea-2-0/setup.deb.sh' | sudo -E bash
    

- name: apt-update
  command: apt update
  changed_when: False


- name: Installing Kea DHCP kea_dhcp_packages
  become: true
  ansible.builtin.apt:
    name: "{{ kea_dhcp_packages }}"
    state: present
  register: result
  until: result is successful

- import_tasks: config.yml 