---
- name: Installing Pre-Reqs
  ansible.builtin.apt:
    name: "{{ kea_pre_reqs }}"
    state: present
  become: true
  register: result
  until: result is successful

- name: debian | Adding Kea DHCP Repo Key
  apt_key:
    url: https://dl.cloudsmith.io/public/isc/kea-2-0/gpg.8029D4AFA58CBB5E.key
    state: present
  become: true

- name: debian | Adding Kea DHCP Repo
  apt_repository:
    repo: https://dl.cloudsmith.io/public/isc/kea-2-0/deb/ubuntu focal main
    state: present
  become: true

- name: Installing Kea DHCP kea_dhcp_packages
  become: true
  ansible.builtin.apt:
    name: "{{ kea_dhcp_packages }}"
    state: present
  register: result
  until: result is successful

- import_tasks: config.yml 