---
# tasks file for operator
  - name: Create {{ operator }} 
    become: true
    user:
      name: "{{ operator }}"
      home: "{{ operator_home_directory }}"
      shell: "{{ operator_shell }}"
      create_home: true

  - name: Add {{ operator }} user to the sudoers
    become: true
    copy:
      dest:  "/etc/sudoers.d/{{ operator }}"
      content:  "{{ operator }}  ALL=(ALL) ALL"
    when: operator_sudo_rights|bool == true

  - name: Deploy SSH key To {{ operator }} 
    become: true
    authorized_key: 
      user: "{{ operator }}"
      key: "{{ item }}"
      state: present 
    with_items: "{{ operator_public_ssh_keys }}"
