# this playbook is meant to install the roles that are assigned in the host var files
---
 - hosts: testnode
   name: Install roles on test node
   tasks:
    - name: include development roles
      include_role:
        name: 
          - nginx_ubuntu

       