# this playbook is meant to install the roles that are assigned in the host var files
# kek
---
 - hosts: testnode
   name: Install roles on test node
   vars:
      role_path: /opt/ansible/code/development/role
   role:
      name: install test role of nginx
      role: "/opt/ansible/code/development/role/nginx"
       