# this playbook is meant to install the roles that are assigned in the host var files
---
 - hosts: testnode
   name: Install roles on test node
   var:
      role_path: /opt/ansible/code/development/role
   tasks:
    - name: include development roles
      include_role:
        name: 
          - "{{ role_path }}/nginx_ubuntu"
       