---
  - hosts: ansbile_servers

    tasks:
      - name: Create ansible-op user
        user:
          name: "ansible-op"
          create_home: true
          home: "/opt/ansible"
          shell: "/bin/bash"
