# A playbook to deploy the code from the ansible repository
# This code setup the keys and repositories
#
#
# Note:
# For this code to work
# The Ansible operator key.pub must excist within the repository,
# Or the repository has to be a public repository
#
#
# Note:
# This command was made to test this playbook
---
- hosts: ansbile_servers
  name: Deploy ansible repository
  vars:
    branches:
      - name: main
        required: true
      - name: testing
        required: true
      - name: developing
        required: true
    repository_path: "git@github.com:MarcHoog/Ansible.git"

  tasks:
    - name: clone ansible repository
      ansible.builtin.git:
        repo: "{{ repository_path }}" 
        dest: "/opt/ansible/{{ item.name }}"
        version: "{{ item.name }}"
        clone: true
        force: yes  
        update: true

      when: item.required == true
      loop: "{{ branches }}"