# A playbook to deploy the code from the ansible repository
# This code just pulls and clones the defined repo
# ! Make sure the repo is always accesible
---
- hosts: ansbile_servers
  name: Deploy ansible repository
  vars:
    repository_path: "git@github.com:MarcHoog/Ansible.git"
    branches:
      - "main"
      - "development"


# Finds all branche folders that are not in defined here
  tasks:
    - name: capture unused branches
      ansible.builtin.find:
        paths: "/opt/ansible/code"
        file_type: directory
        exclude: "{{ branches }}"

      register: found_files

# Removes branches that are still in the code folder but not defind here
    - name: remove unused branches
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: absent
      
      with_files: "{{ found_files}}"

# Clones/Updates the branches that are defined here
    - name: clone / update ansible repository and branches
      ansible.builtin.git:
        repo: "{{ repository_path }}" 
        dest: "/opt/ansible/code/{{ item }}"
        version: "{{ item }}"
        clone: true
        force: yes  
        update: true
     
      register: git_result
      ignore_errors: true
      loop: "{{ branches }}"
      
# Prints the Gire results
    - name: GIT results
      ansible.builtin.debug:
        msg: "{{ git_result }}"

# TODO LOG THESE RESULTS SOMEWHERE

