# A playbook to deploy the code from the ansible repository
# This code setup the keys and repositories
#
#
# Note:
# For this code to work
# The Ansible operator key.pub must excist within the repository,
# Or the repository has to be a public repository
#
#
# Note:
# This command was made to test this playbook
---
- hosts: ansbile_servers
  name: Deploy ansible repository
  vars:
    branches:
      - "main"
      - "development"
    repository_path: "git@github.com:MarcHoog/Ansible.git"

# Finds all branche folders that are not in defined here
  tasks:
    - name: capture unused branches
      ansible.builtin.find:
        paths: "/opt/ansible/code"
        file_type: directory
        exclude: "{{ branches }}"

      register: found_files

# Removes branches that are still in the code folder but not defind here
    - name: remove unused branches
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ found_files['files'] }}"

# Clones/Updates the branches that are defined here
    - name: clone / update ansible repository and branches
      ansible.builtin.git:
        repo: "{{ repository_path }}" 
        dest: "/opt/ansible/code/{{ item }}"
        version: "{{ item }}"
        clone: true
        force: yes  
        update: true
      register: git_result
      ignore_errors: true
      loop: "{{ branches }}"
      
# Prints the Gire results
    - name: GIT results
      ansible.builtin.debug:
        msg: "{{ git_result }}"

