# A playbook to deploy the code from the ansible repository
# This code setup the keys and repositories
#
#
# Note:
# For this code to work
# The Ansible operator key.pub must excist within the repository,
# Or the repository has to be a public repository
#
#
# Note:
# This command was made to test this playbook
---
- hosts: ansbile_servers
  name: Deploy ansible repository
  vars:
    branches:
      - "main"
      - "development"
    repository_path: "git@github.com:MarcHoog/Ansible.git"

  tasks:
    - name: capture unused branches
      ansible.builtin.find:
        paths: "/opt/ansible/code"
        file_type: directory
        exclude: branches
      
      register: found_files

    - name: remove unused brances
      file:
        path: "{{ item.path }}"
        state: absent
#      debug:
#        msg: "{{ item }}"
      ansible.builtin.with_items: "{{ found_files }}"

    - name: clone / update ansible repository and branches
      ansible.builtin.git:
        repo: "{{ repository_path }}" 
        dest: "/opt/ansible/code/{{ item }}"
        version: "{{ item }}"
        clone: true
        force: yes  
        update: true

      loop: "{{ branches }}"