# e.g. Ubuntu 20.04 (Focal Fossa):
#
# deb https://nginx.org/packages/ubuntu/ focal nginx
# deb-src https://nginx.org/packages/ubuntu/ focal nginx
# To install the packages, execute in your shell:

# sudo apt update
# sudo apt install nginx
# If a W: GPG error: https://nginx.org/packages/ubuntu focal InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY $key is encountered during the NGINX repository update, execute the following:

## Replace $key with the corresponding $key from your GPG error.
# sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys $key
# sudo apt update
# sudo apt install nginx
# You have now nginx installed on your server but not ready to serve web pages. you have to start the nginx. You can do this by using this command:
# 
# sudo systemctl start nginx
#
---
 - name: cleanup of apt
   ansible.builtin.apt:
    autoclean: yes
    autoremove: yes
#  tags: apt

 - name: install nginx
   ansible.builtin.apt:
    name: nginx
    state: latest
    update_cache: yes
#   tags: apt

 - name: Ensures nginx_conf_path exsists
   file:
     path: "{{ nginx_conf_path }}"

 - name: Ensure nginx is started and enabled to start at boot
   service: name=nginx state=started