- name: add helm repository for celium
  kubernetes.core.helm_repository:
    name: cilium
    repo_url: https://helm.cilium.io/

- name: helm install cilium
  kubernetes.core.helm:
    name: cilium
    chart_ref: cilium/cilium 
    chart_version: 1.11.5
    release_namespace: kube-system
    values:
      hubble:
        relay:
          enabled: true
        ui:
          enabled: true

# SHOULD CHECK CHECKSUM OF THIS PACKAGE BUT, YEH NOH
- name: get the cilium CLI Package
  get_url:
    url: "https://github.com/cilium/cilium-cli/releases/latest/download/cilium-linux-amd64.tar.gz"
    dest: /tmp/cilium.tar.gz

- name: Extract cilium.tar.gz into /usr/local/bin
  become: true
  ansible.builtin.unarchive:
    src: /tmp/cilium.tar.gz
    dest: /usr/local/bin
    remote_src: yes

- name: cilium connectivity test command
  shell:
    cmd: cilium status
  register: ciliumResult

- name: Printing Cilium result command
  debug:
    msg: ciliumResult


