---
- name: add helm repository for celium
  kubernetes.core.helm_repository:
    name: cilium
    repo_url: https://helm.cilium.io/

- name: helm install cilium
  kubernetes.core.helm:
    name: cilium
    chart_ref: cilium/cilium 
    chart_version: 1.11.5
    release_namespace: kube-system
    values:
      k8sServiceHost: kube-master00
      k8sServicePort: 6443
      hubble:
        relay:
          enabled: true
        ui:
          enabled: true
