---
- name: add helm repository for celium
  kubernetes.core.helm_repository:
    name: cilium
    repo_url: https://helm.cilium.io/

- name: helm install cilium
  kubernetes.core.helm:
    name: cilium
    chart_ref: cilium/cilium 
    chart_version: 1.11.5
    release_namespace: kube-system
    values:
      k8sServiceHost: 10.8.0.1
      k8sServicePort: 6443
      kubeProxyReplacement: strict
      externalIPs:
        enabled: true
      hostFirewall: false
      ipam:
        mode: kubernetes
      k8s:
        requireIPv4PodCIDR: true
      egressGateway:
        enabled: true
      bpf:
        masquerade: true
      # Needed to replace kube-proxy
      hostServices:
        enabled: true
        protocols: tcp,udp
      nodePort:
        enabled: true
        bindProtection: true
        autoProtectPortRange: true