- name: add helm repository for celium
  kubernetes.core.helm_repository:
    name: cilium
    repo_url: https://helm.cilium.io/

- name: helm install cilium
  kubernetes.core.helm:
    name: cilium
    chart_ref: cilium/cilium 
    chart_version: 1.11.5
    release_namespace: kube-system

- name: get the cilium CLI Package
  get_url:
    url: "https://github.com/cilium/cilium-cli/releases/latest/download/cilium-linux-amd64.tar.gz{,.sha256sum}"
    dest: "/tmp/cilium.tar.gz"
    checksum_algorithm: sha256sum
    get_checksum: yes

- name: Extract cilium.tar.gz into /usr/local/bin
  ansible.builtin.unarchive:
    src: /tmp/cilium.tar.gz
    dest: /usr/local/bin

- name: cilium connectivity test command
  shell:
    cmd: cilium connectivity test
  register: ciliumResult

- name: Printing Cilium result command
  debug:
    msg: ciliumResult


