---
# SHOULD CHECK CHECKSUM OF THIS PACKAGE BUT, YEH NOH
- name: get the cilium CLI Package
  get_url:
    url: "https://github.com/cilium/cilium-cli/releases/latest/download/cilium-linux-amd64.tar.gz"
    dest: /tmp/cilium.tar.gz

- name: Extract cilium.tar.gz into /usr/local/bin
  become: true
  ansible.builtin.unarchive:
    src: /tmp/cilium.tar.gz
    dest: /usr/local/bin
    remote_src: yes

