---
- name: install qemu-guest-agent
  block:
    - name: apt-update
      command: apt update
      changed_when: False
      register: result
      until: result is successful
      delay: 6
      retries: 10

    - name: install qemu quest agent on all machines
      ansible.builtin.apt:
        name: qemu-guest-agent
        state: present
      register: qemu_installed

    - name: reboot when qemu is just installed 
      reboot:
      when: qemu_installed.changed

    - name: ensure Qemu guest agent is running on all machines. 
      ansible.builtin.systemd:
        state: started
        enabled: yes
        name: qemu-guest-agent
  become: true