---
- name: Make nfs-subdir the main storage client
  hosts: kube-master00
  gather_facts: false
  tasks:
    
    - name: doing some kube shit
      k8s:
        state: present
        kind: StorageClass
        name: nfs-client
        definition:
          metadata:
            annotations:
              storageclass.kubernetes.io/is-default-class: "true"
              
  

