---
- name: Make nfs-subdir the main storage client
  hosts: kube-master00
  tasks:
    
    - name: doing some kube shit
      k8s:
        apply: true
        force: true
        state: present
        kind: StorageClass
        name: nfs-client
        definition:
          metadata:
            annotations:
              Storageclass.kubernetes.io/is-default-class: "False"
  

