---
- name: Install helm on master node
  hosts: kube-master00
  tasks:
    block:
      - name: add helm key
        ansible.builtin.apt_key:
          url: https://baltocdn.com/helm/signing.asc

      - name: apt install dependencies
        ansible.builtin.apt:
          name: apt-transport-https
          state: present

      - name: Add helm respository
        ansible.builtin.apt_repository:
          repo: deb https://baltocdn.com/helm/stable/debian/ all main

      - name: Update aptitude cache
        ansible.builtin.apt:
          update_cache: true
          

      - name: Install helm
        ansible.builtin.apt:
          name: helm
          state: present
      

    