---
- name: Make nfs-subdir the main storage client
  hosts: kube-master00
  tasks:
      
    - name: Install required package
      become: true
      ansible.builtin.apt: 
        name: pip
        state: present

    - name: Install Python pre-requisits
      pip:
        name:
          - openshift
          - pyyaml>3.11
          - kubernetes==18.20.0 

    - name:
      become: true
      k8s:
        kubeconfig: /root/.kube/config
        definition:
          apiVersion: storage.kys.io/v1
          kind: Storageclass
          metadata:
            name: nfs-client
            annotations:
              Storageclass.kubernetes.io/is-default-class: "false"
          provisioner: cluster.local/nfs-subdir-external-provisioner
  
  