---
- name: Make nfs-subdir the main storage client
  hosts: kube-master00
  tasks:
    - name: doing some kube shit
      kubernetes.core.k8s_json_patch:
        kind: StorageClass
        name: nfs-client
        patch:
          - op: replace
            patch: Storageclass.kubernetes.io/is-default-class
            value: False