---
- name: Make nfs-subdir the main storage client
  hosts: kube-master00
  tasks:
    # CHANGES TO PLAYBOOK OR ROLE LATER

    - name: Install required package
      become: true
      ansible.builtin.apt: 
        name: pip
        state: present

    - name: Install Python pre-requisits
      pip:
       name:
        - openshift
        - pyyaml>3.11
        - kubernetes>=12.00.0 
      vars:
        ansible_python_interpreter: /usr/bin/python3
    
    - name:
      become: true
      k8s:
        definition:
          apiVersion: storage.kys.io/v1
          kind: Storageclass
          metadata:
            name: nfs-client
            annotations:
              Storageclass.kubernetes.io/is-default-class: "false"
          provisioner: cluster.local/nfs-subdir-external-provisioner
  
  