---
- name: Make nfs-subdir the main storage client
  hosts: kube-master00
  tasks:
    - name:
      k8s:
        kubeconfig: ~/.kube/config
        host: https://10.8.0.1:6443
        verify_ssl: false 
        definition:
          apiVersion: storage.kys.io/v1
          kind: Storageclass
          metadata:
            name: nfs-client
            annotations:
              Storageclass.kubernetes.io/is-default-class: "false"
          provisioner: cluster.local/nfs-subdir-external-provisioner
  
  