---
  - hosts: kubernetes_masters
    become: true
    gather_facts: false
    tasks:
      - name: get join command
        shell: kubeadm token create --print-join-command
        register: join_command_raw

      - name: set join command
        set_fact:
          join_command: "{{ join_command_raw.stdout_lines[0] }}"


  - hosts: kubernetes_workers
    become: true
    tasks:

      - name: store the statistics of ansible-op/.ansible/node_joined.txt in the 'out' variable
        stat:
          path: /home/ansible-op/.ansible/node_joined.txt 
        register: node_joined

      - name: join cluster
        shell: "{{ hostvars['kube-master00'].join_command }} >> /home/ansible-op/.ansible/node_joined.txt"
        args:
          chdir: $HOME
          creates: node_joined.txt
        when: node_joined.stat.exists == false
