---
  - name: control_node.yml
    block:
      - name: Install control plane
        become: true
        apt:
          name: kubectl
          state: present
          force: yes
        register: control_plane
  
      - name: initialize the cluster
        shell: kubeadm init --pod-network-cidr=10.244.0.0/16
        args:
          chdir: $HOME
          creates: cluster_initialized.txt
        when: control_plane.changed

      - name: create .kube directory
        become: true
        become_user: ansible-op
        file:
          path: $HOME/.kube
          state: directory
          mode: 0755

      - name: copy admin.conf to user's kube config
        copy:
          src: /etc/kubernetes/admin.conf
          dest: /home/ansible-op/.kube/config
          remote_src: yes
          owner: ansible-op

      - name: install Pod network
        become: true
        become_user: ansible-op
        shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml >> pod_network_setup.txt
        args:
          chdir: $HOME
          creates: pod_network_setup.txt
        when: control_plane.changed
          
    become: true 