---  
  - name: installs docker as the container runtime 
    block:
      - name: Create Docker config directory
        file:
          path: "/etc/docker"
          state: directory
        
      - name: Changing Docker to systemd driver
        copy:
          dest: /etc/docker/daemon.json
          content: |
              {
              "exec-opts": ["native.cgroupdriver=systemd"]
              }
        
      - name: Install Docker
        apt:
          name: docker.io
          state: present
          update_cache: true
    become: true