---
- include_tasks: runtime-containerd-setup.yml
  when: runtime == "containerd"

- include_tasks: runtime-docker-setup.yml
  when: runtime == "docker"

- include_tasks: node-base-setup.yml

- include_tasks: control_node.yml
  when: role == "controller"
