---
  - name: Create {{ operator }} (When configured)
    become: true
    user:
      name: "{{ operator }}"
      shell: "/bin/bash"
      create_home: true
    
    when: "operator == true"
    

  - name: Add {{ operator }} user to the sudoers (When configured)
    become: true
    copy:
      dest:  "/etc/sudoers.d/{{ operator }}"
      content:  "{{ operator }}  ALL=(ALL) ALL"
    
    when: "operator == true"

  - name: Deploy SSH key To {{ operator }} (When configured)
    become: true
    authorized_key: 
      user: "{{ operator }}"
      key: "{{ item }}"
      state: present
    
    with_items: "{{ operator_public_ssh_keys }}"
    
    when: "operator == true"

  - name: add hashicorp key
    become: true
    ansible.builtin.apt_key:
      url: "{{ hashicorp_key }}"
      state: present

  - name: add hashicorp repository
    become: true
    ansible.builtin.apt_repository:
      repo: "{{ repository_path }}"
      state: present

  - name: installing terraform
    become: true
    ansible.builtin.apt: 
      name: terraform
      state: latest
      update_cache: true

# tasks file for foo