---
    - name: Creating the user {{ ansible_operator }}
      become: true
      user:
        name:  "{{ ansible_operator }}"
        create_home: true
        move_home: true
        shell: "/bin/bash"

    - name: Add {{ ansible_operator }} user to the sudoers
      become: true
      copy:
        dest:  "/etc/sudoers.d/{{ ansible_operator }}"
        content:  "{{ ansible_operator }}  ALL=(ALL)  NOPASSWD: ALL"

    - name: Deploy SSH Key to remote Machine
      authorized_key:  user={{ ansible_operator }}
                       key="{{ ansible_public_key }}"
                       state=present

    - name: Disable Password Authentication for all users
      become: true
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication'
        line: "PasswordAuthentication no"
        state: present
        backup: true


    - name: Disable Root Login
      become: true
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: "PermitRootLogin no"
        state: present
        backup: true
      notify: restart ssh
      when: inventory_hostname != ansible
      

# tasks file for python_webhook