---
docker_repository_path: "deb [arch={{ system_architecture }}] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
docker_repository_key: "https://download.docker.com/linux/ubuntu/gpg"

contained_dependencys: [gnupg2, software-properties-common, apt-transport-https, ca-certificates]