---
- name: install service
  ansible.builtin.apt:
    name: "{{ics_dhcp_packages }}"
    state: present
    update_cache: true

- name: ensure directory excists
  file:
    path: "{{ics_dhcp_conf_dir}}"
    state: directory
    mode: 755
    group: root
    owner: root

- name: create dhcp.conf
  template:
    src: dhcp.j2
    dest: "{{ ics_dhcp_config }}"
    owner: root
    group: root
    mode: 0644
  notify: reload dhcp