---
- name: export awx configuration
  hosts: localhost
  debugger: on_failed
  gather_facts: false
  tasks:
  - name: export 
    awx.awx.tower_export:
      controller_host: 127.0.0.1:30080
      validate_certs: no
      tower_username: admin
      tower_password: jnVIQf5Lj7ihtNAFLvvarWsDxgeKECVt
      all: true
    register: out

  - name: debug awx configuration
    debug: 
      var: out
      verbosity: 3      
