---
- name: export awx file
  hosts: ansible
  tasks:

  - name: export  awx configuration
    awx.awx.tower_export:
      controller_host: "{{ controller_host }}"
      validate_certs: "{{ validate_certs }}"
      tower_username: "{{ tower_username }}"
      tower_password: "{{ tower_password }}"
      all: true
    register: template_assets
  
  - copy: 
      content: "{{ template_assets | to_nice_json }}" 
      dest: "/tmp/export"
