---
- name: export awx configuration
  hosts: localhost
  debugger: on_failed
  gather_facts: false
  tasks:
  - name: export 
    awx.awx.tower_export:
      all: true
    register: out

  - name: debug awx configuration
    debug: 
      var: out
      verbosity: 3      
