---
- name: export awx configuration
  hosts: localhost
  gather_facts: false
  tasks:
  - name: export 
    awx.awx.tower_export:
      controller_host: http://10.8.0.1:30080/
      validate_certs: no
      tower_username: admin
      tower_password: jnVIQf5Lj7ihtNAFLvvarWsDxgeKECVt
      all: true
    register: template_assets

  - name: debug awx configuration
    debug: 
      var: template_assets
      verbosity: 3
  
  - copy: content="{{ template_assests }}" dest=/tmp/test
