---
- name: export awx configuration
  hosts: localhost
  gather_facts: false
  tasks:
  - name: export 
    awx.awx.tower_export:
      controller_host: "{{ controller_host }}"
      validate_certs: "{{ validate_certs }}"
      tower_username: "{{ tower_username }}"
      tower_password: "{{ tower_password }}"
      all: true
    register: template_assets

  - name: debug awx configuration
    debug: 
      var: template_assets
      verbosity: 3
  
  - copy: 
      content: "{{ template_assets | to_nice_json }}" 
      dest: /tmp/test
