---
- name: import awx settings from file
  hosts: ansible
  tasks:

  - name: import awx settings from file
    awx.awx.tower_import:
      controller_host: "{{ controller_host }}"
      validate_certs: "{{ validate_certs }}"
      tower_username: "{{ tower_username }}"
      tower_password: "{{ tower_password }}"
      assets: "{{ lookup('file', '/tmp/export') | from_json() }}"
    