---
- name: check dhcp4 config
  changed_when: False
  command:  
    cmd: "kea-dhcp4 -t {{ kea_path }}/{{ kea_dhcp4_conf }}"

- name: check dhcp6 config
  changed_when: False
  command: 
    cmd: "kea-dhcp6 -t {{ kea_path }}/{{ kea_dhcp6_conf }}"

- name: check dhcp-ddns config
  changed_when: False
  command: 
    cmd: "kea-dhcp-ddns -t {{ kea_path  }}/{{ kea_dhcp_ddns_conf }}"

- name: restart kea-dhcp
  service:
    name: "{{ item['name'] }}"
    state: restarted
  become: true
  loop: "{{ kea_dhcp_services }}"
  when:
    - item['enabled']|bool

#- name: restart kea-dhcp