---
- name: Install some harmless packages on my Ubuntu testing nodes
  hosts: testnode
  vars:
    packages:
      - name: tree
        required: true
      - name: cmatrix
        required: true
  
  tasks: 
    - name: Install "{{ item.name }}" on Debian
      apt:
        name: "{{ item.name }}"
        state: present
      
      when: ansible_os_family == "Debian"   and
            item.required == true

      loop: "{{ packages }}"