#   Pre work

# If there is No user yet called sysop
#   sudo -i
#   useradd -m -s /bin/bash sysop
#   passwd Doekoe2020!
#   echo -e ‘sysop\tALL=(ALL)\tNOPASSWD:\tALL’ > /etc/sudoers.d/sysop
---
- hosts: all
  vars:
    public_key: "{{ lookup('file', '/opt/ansible/.ssh/id_ed25519.pub') }}"  
  gather_facts: true
  become: true
  
  tasks:
    - name: Creating the user ansible-op
      user:
        name:  "ansible-op"
        create_home: true
        shell: "/bin/bash"

    - name: Add ansible-op user to the sudoers
      copy:
        dest:  "/etc/sudoers.d/ansible-op"
        content:  "ansible-op  ALL=(ALL)  NOPASSWD: ALL"

    - name: Deploy SSH Key to remote Machine
      authorized_key:  user=ansible-op
                       key="{{ public_key }}"
                       state=present

    - name: Disable Password Authentication for all users
      lineinfile:
          path: /etc/ssh/sshd_config
          regexp: '^PasswordAuthentication'
          line: "PasswordAuthentication no"
          state: present
          backup: true

    - name: Disable Root Login
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: "PermitRootLogin no"
        state: present
        backup: true
      notify:
        - Restart ssh

  handlers:
    - name: Restart ssh
      service:
        name: sshd
        state: restarted
